apiVersion: v1
kind: Pod
metadata:
  name: cm-secret-pod

spec:
  containers:
  - name: database
    image: registry.redhat.io/rhel8/mysql-80:1
    ports:
    - containerPort: 3306
      name: db-port
    env:
    - name: MYSQL_USER
      valueFrom:
        configMapKeyRef:
          name: micheal-cm
          key: user
      #value: user1
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: micheal-cm
          key: database
      #value: items

    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: root_password
          name: lucien-secret
      #value: r00tpa55
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: lucien-secret
      #value: mypa55
