apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "dev-limits"
spec:
  limits:
  - type: "Pod"
    max:
      cpu: "100m"
      memory: "750Mi"
    min:
      cpu: "10m"
      memory: "5Mi"
  - type: "Container"
    max:
      cpu: "100m"
      memory: "750Mi"
    min:
      cpu: "10m"
      memory: "5Mi"
    default:
      cpu: "100m"
      memory: "100Mi"
    defaultRequest:
      cpu: "20m"
      memory: "20Mi"
  - type: openshift.io/Image
    max:
      storage: 1Gi
