apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  #nfs-storage
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /exports-ocp4/web
    server: 192.168.50.254
